# Processing per capita

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\student\Desktop\Manufacturing_Trends\data\bls.gov\employment\raw\01.csv", delimiter='\t')
df.head()

,series_id,state,area,year,period,month,value
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1.1
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1.1
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1.1
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1.1
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1.1

In [6]:
df.value = df.value * 1000

In [7]:
df.head()

,series_id,state,area,year,period,month,value
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1100.0
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1100.0
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1100.0
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1100.0
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1100.0

In [23]:
df_pop = pd.read_csv(r"C:\Users\student\Desktop\Manufacturing_Trends\data\census.gov\USpop2020-2025.csv")
df_pop.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,...,RDOMESTICMIG2021,RDOMESTICMIG2022,RDOMESTICMIG2023,RDOMESTICMIG2024,RDOMESTICMIG2025,RNETMIG2021,RNETMIG2022,RNETMIG2023,RNETMIG2024,RNETMIG2025
0,10,0,0,0,United States,331516113,331578104,332100166,333996304,336755052,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.133157,5.020630,6.751047,8.081071,3.702620
1,20,1,0,0,Northeast Region,57617560,57436027,57234503,57174375,57458539,...,-5.035383,-7.452027,-4.783077,-3.107894,-3.544532,-3.632267,-1.425326,4.125517,7.384999,0.704071
2,30,1,1,0,New England,15122087,15047713,15116021,15178293,15267275,...,2.864433,-2.549587,-1.971584,-0.870354,-1.791240,4.636760,4.712898,6.032734,7.954870,2.800945
3,30,1,2,0,Middle Atlantic,42495473,42388314,42118482,41996082,42191264,...,-7.855132,-9.217667,-5.799826,-3.917263,-4.179011,-6.583802,-3.636041,3.435790,7.178864,-0.054742
4,20,2,0,0,Midwest Region,68999462,68979566,68867096,68872112,69132050,...,-2.545350,-2.623233,-1.327003,-0.630161,0.230326,-1.743053,0.551433,3.237294,4.892725,2.817342

In [28]:
state_codes = pd.read_csv(r"C:\Users\student\Desktop\Manufacturing_Trends\src\Data Gathering\bls.gov\employment\sm.state.txt", delimiter='\t')
state_codes.head()

   state_code  state_name
0           0  All States
1           1     Alabama
2           2      Alaska
3           4     Arizona
4           5    Arkansas

In [30]:
state_codes_dict = {}
for code, name in zip(state_codes.state_code, state_codes.state_name):
    state_codes_dict[code] = name

In [ ]:
df_pop['STATE_NAME'] = [state_codes_dict[int(state)] for state in df_pop.STATE]
#for state in df_pop.STATE:
#    print(state, state_codes_dict[state])

In [35]:
state_set = set(df.state)

In [49]:
rows = []

for state in state_set:
    subset = df[df.state == state]
    year_2020 = subset[subset.year == 2020]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2020
    year_2020['per_capita'] = year_2020.value.astype('int') / population
    rows.append(year_2020)

    year_2021 = subset[subset.year == 2021]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2021
    year_2021['per_capita'] = year_2021.value.astype('int') / population
    rows.append(year_2021)

    year_2022 = subset[subset.year == 2022]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2022
    year_2022['per_capita'] = year_2022.value.astype('int') / population
    rows.append(year_2022)

    year_2023 = subset[subset.year == 2023]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2023
    year_2023['per_capita'] = year_2023.value.astype('int') / population
    rows.append(year_2023)

    year_2024 = subset[subset.year == 2024]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2024
    year_2024['per_capita'] = year_2024.value.astype('int') / population
    rows.append(year_2024)

    year_2025 = subset[subset.year == 2025]
    population = df_pop[df_pop.STATE_NAME == state].iloc[0].POPESTIMATE2025
    year_2025['per_capita'] = year_2025.value.astype('int') / population
    rows.append(year_2025)

C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2024['per_capita'] = year_2024.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2025['per_capita'] = year_2025.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2020['per_capita'] = year_2020.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2021['per_capita'] = year_2021.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2022['per_capita'] = year_2022.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2023['per_capita'] = year_2023.value.astype('int') / population
C:\Users\student\AppData\Local\Temp\ipykernel_1832\2920325415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
adjusted_per_capita = pd.concat(rows)
adjusted_per_capita.head()

,series_id,state,area,year,period,month,value,per_capita
5760,SMU05229003000000001,Arkansas,"Fort Smith, AR-OK",2020,M12,December,15800.0,0.005242
5761,SMU05229003000000001,Arkansas,"Fort Smith, AR-OK",2020,M11,November,15800.0,0.005242
5762,SMU05229003000000001,Arkansas,"Fort Smith, AR-OK",2020,M10,October,15800.0,0.005242
5763,SMU05229003000000001,Arkansas,"Fort Smith, AR-OK",2020,M09,September,15800.0,0.005242
5764,SMU05229003000000001,Arkansas,"Fort Smith, AR-OK",2020,M08,August,15600.0,0.005175

In [53]:
adjusted_per_capita.to_csv(r"C:\Users\student\Desktop\Manufacturing_Trends\data\bls.gov\employment\processed\01_per_capita_2020-2025.csv")