In [1]:
import pandas as pd

In [2]:
employment_data = pd.read_csv(r"..\data\bls.gov\employment\raw\01.csv", delimiter='\t')
employment_data.head()

,series_id,state,area,year,period,month,value
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1.1
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1.1
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1.1
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1.1
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1.1

In [3]:
employment_data = employment_data[employment_data.year == 2022]
employment_data.head()

,series_id,state,area,year,period,month,value
36,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M12,December,1.2
37,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M11,November,1.2
38,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M10,October,1.2
39,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M09,September,1.3
40,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M08,August,1.3

In [4]:
employment_data_by_state = employment_data.groupby('state').value.sum()
employment_data_by_state.head()

state
Alabama        2047.6
Alaska           35.1
Arizona        2278.3
Arkansas        784.6
California    22703.4
Name: value, dtype: float64

In [6]:
employment_data_by_state = employment_data_by_state.reset_index()
employment_data_by_state.head()

        state    value
0     Alabama   2047.6
1      Alaska     35.1
2     Arizona   2278.3
3    Arkansas    784.6
4  California  22703.4

In [7]:
employment_data_by_state.to_csv(r"../data/bls.gov/employment/processed/01_employment_2022_by_state.csv")