# Adjusting Robotics Investment Data to be Per Worker

In [7]:
import pandas as pd

### Load and Adj employment data

In [8]:
employment_data = pd.read_csv(r"..\data\bls.gov\employment\raw\01.csv", delimiter='\t')
employment_data.head()

,series_id,state,area,year,period,month,value
0,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M12,December,1.1
1,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M11,November,1.1
2,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M10,October,1.1
3,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M09,September,1.1
4,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2025,M08,August,1.1

In [14]:
employment_data = employment_data[employment_data.year == 2022]
employment_data.head()

,series_id,state,area,year,period,month,value
36,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M12,December,1.2
37,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M11,November,1.2
38,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M10,October,1.2
39,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M09,September,1.3
40,SMU15279803000000001,Hawaii,"Kahului-Wailuku, HI",2022,M08,August,1.3

In [17]:
employment_data_by_state = employment_data.groupby('state').value.sum()
employment_data_by_state.head()

state
Alabama        2047.6
Alaska           35.1
Arizona        2278.3
Arkansas        784.6
California    22703.4
Name: value, dtype: float64

In [23]:
employment_data_dict = employment_data_by_state.to_dict()

USA_total = sum(employment_data_dict.values())
employment_data_dict['United States'] = USA_total

### Load Robotics Investment Data

In [28]:
investment_data = pd.read_csv(r"..\data\census.gov\robotics_ce_by_state_2022.csv", delimiter='\t')
investment_data.columns = ["State", "2022_Robotics_CE"]
investment_data['2022_Robotics_CE'] = investment_data["2022_Robotics_CE"].astype('float')
investment_data.head()

           State  2022_Robotics_CE
0  United States         3905000.0
1        Alabama          223500.0
2         Alaska            1927.0
3        Arizona           63170.0
4       Arkansas           44990.0

# Calculating Adjusted CE

In [29]:
investment_data['CE_adjusted'] = investment_data['2022_Robotics_CE'] / investment_data['State'].map(employment_data_dict)
investment_data.head()

           State  2022_Robotics_CE  CE_adjusted
0  United States         3905000.0    24.960992
1        Alabama          223500.0   109.152178
2         Alaska            1927.0    54.900285
3        Arizona           63170.0    27.726814
4       Arkansas           44990.0    57.341320

In [30]:
investment_data.to_csv(r"..\data\census.gov\processed\robotics_ce_by_state_2022_adjusted.csv", index=False)